name: CI

on:
  push:
    branches:
      - main
      - dev
      - dev-frontend
      - dev-backend
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Lint, Typecheck, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate --schema=apps/api/prisma

      - name: Lint
        run: npx turbo run lint

      - name: Typecheck
        run: npx turbo run check-types

      - name: Build
        run: npx turbo run build

      - name: Test
        run: npx turbo run test
        env:
          CI: true
